version: '2.1'
services:
    mysql:
        image: custom-mysql:latest
        ports:
                - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    spring-boot:
        image: springcrud-tomcat:latest
        ports:
                - "8080:8080"
        links:
            - mysql
        depends_on:
            mysql:
                condition: service_healthy
        